services:
  - type: web
    name: Prestalink
    rootDir: backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
